"""Add company financial table

Revision ID: 1495f19c8162
Revises: a7fcd5032ef6
Create Date: 2025-04-11 07:43:09.443756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1495f19c8162'
down_revision: Union[str, None] = 'a7fcd5032ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_symbol', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('revenue_breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_financials_company_symbol'), 'company_financials', ['company_symbol'], unique=False)
    op.create_index(op.f('ix_company_financials_id'), 'company_financials', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_financials_id'), table_name='company_financials')
    op.drop_index(op.f('ix_company_financials_company_symbol'), table_name='company_financials')
    op.drop_table('company_financials')
    # ### end Alembic commands ###
