"""add new CompanyInsight table

Revision ID: 28b6f4326736
Revises: 36348ff272b8
Create Date: 2025-04-22 20:27:56.792127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b6f4326736'
down_revision: Union[str, None] = '36348ff272b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_symbol', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('insight_type', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_insights_company_symbol'), 'company_insights', ['company_symbol'], unique=False)
    op.create_index(op.f('ix_company_insights_id'), 'company_insights', ['id'], unique=False)
    op.create_index(op.f('ix_company_insights_slug'), 'company_insights', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_insights_slug'), table_name='company_insights')
    op.drop_index(op.f('ix_company_insights_id'), table_name='company_insights')
    op.drop_index(op.f('ix_company_insights_company_symbol'), table_name='company_insights')
    op.drop_table('company_insights')
    # ### end Alembic commands ###
