"""add new CompanyQuarterlyFinancialStatement table

Revision ID: 36348ff272b8
Revises: 42abe5399cb3
Create Date: 2025-04-16 07:56:01.180468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36348ff272b8'
down_revision: Union[str, None] = '42abe5399cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_quarterly_financial_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_symbol', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('period_end_quarter', sa.String(), nullable=True),
    sa.Column('balance_sheet', sa.JSON(), nullable=True),
    sa.Column('income_statement', sa.JSON(), nullable=True),
    sa.Column('cash_flow', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_quarterly_financial_statement_company_symbol'), 'company_quarterly_financial_statement', ['company_symbol'], unique=False)
    op.create_index(op.f('ix_company_quarterly_financial_statement_id'), 'company_quarterly_financial_statement', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_quarterly_financial_statement_id'), table_name='company_quarterly_financial_statement')
    op.drop_index(op.f('ix_company_quarterly_financial_statement_company_symbol'), table_name='company_quarterly_financial_statement')
    op.drop_table('company_quarterly_financial_statement')
    # ### end Alembic commands ###
