"""add_10k_filing_url_column

Revision ID: 691c9e4db4ae
Revises: 847b2b6962b5
Create Date: 2025-09-07 14:35:18.774017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691c9e4db4ae'
down_revision: Union[str, None] = '847b2b6962b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_financial_statement', sa.Column('filing_10k_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_financial_statement', 'filing_10k_url')
    # ### end Alembic commands ###
