"""add thumbnail_url column to company_insights table

Revision ID: 6fcea9018660
Revises: 28b6f4326736
Create Date: 2025-04-27 10:26:40.336980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fcea9018660'
down_revision: Union[str, None] = '28b6f4326736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_insights', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_insights', 'thumbnail_url')
    # ### end Alembic commands ###
