"""add_unique_constraint_company_financial_statement

Revision ID: 847b2b6962b5
Revises: 5396295efc31
Create Date: 2025-08-17 12:20:15.910979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847b2b6962b5'
down_revision: Union[str, None] = '5396295efc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_company_financial_symbol_year', 'company_financial_statement', ['company_symbol', 'period_end_year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_company_financial_symbol_year', 'company_financial_statement', type_='unique')
    # ### end Alembic commands ###
