"""Add company financial statement table

Revision ID: a7fcd5032ef6
Revises: 
Create Date: 2025-04-11 06:46:46.694335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7fcd5032ef6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_financial_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_symbol', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('period_end_year', sa.Integer(), nullable=True),
    sa.Column('is_ttm', sa.Boolean(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=True),
    sa.Column('balance_sheet', sa.JSON(), nullable=True),
    sa.Column('income_statement', sa.JSON(), nullable=True),
    sa.Column('cash_flow', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_financial_statement_company_symbol'), 'company_financial_statement', ['company_symbol'], unique=False)
    op.create_index(op.f('ix_company_financial_statement_id'), 'company_financial_statement', ['id'], unique=False)
    op.drop_index('ix_company_financials_company_symbol', table_name='company_financials')
    op.drop_index('ix_company_financials_id', table_name='company_financials')
    op.drop_table('company_financials')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_financials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('revenue_breakdown', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='company_financials_pkey')
    )
    op.create_index('ix_company_financials_id', 'company_financials', ['id'], unique=False)
    op.create_index('ix_company_financials_company_symbol', 'company_financials', ['company_symbol'], unique=False)
    op.drop_index(op.f('ix_company_financial_statement_id'), table_name='company_financial_statement')
    op.drop_index(op.f('ix_company_financial_statement_company_symbol'), table_name='company_financial_statement')
    op.drop_table('company_financial_statement')
    # ### end Alembic commands ###
