"""add company fundamental table

Revision ID: b02c543f4bf9
Revises: e41dee7f3d0b
Create Date: 2025-06-11 07:43:58.937637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02c543f4bf9'
down_revision: Union[str, None] = 'e41dee7f3d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_fundamental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_symbol', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_fundamental_company_symbol'), 'company_fundamental', ['company_symbol'], unique=False)
    op.create_index(op.f('ix_company_fundamental_id'), 'company_fundamental', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_fundamental_id'), table_name='company_fundamental')
    op.drop_index(op.f('ix_company_fundamental_company_symbol'), table_name='company_fundamental')
    op.drop_table('company_fundamental')
    # ### end Alembic commands ###
