"""Add filing_10q_url to company_quarterly_financial_statement

Revision ID: c49474451233
Revises: 691c9e4db4ae
Create Date: 2026-01-02 14:51:04.604412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49474451233'
down_revision: Union[str, None] = '691c9e4db4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_quarterly_financial_statement', sa.Column('filing_10q_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_quarterly_financial_statement', 'filing_10q_url')
    # ### end Alembic commands ###
