"""add company insight title column

Revision ID: e41dee7f3d0b
Revises: 6fcea9018660
Create Date: 2025-05-24 21:37:19.333764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41dee7f3d0b'
down_revision: Union[str, None] = '6fcea9018660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_insights', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_insights', 'title')
    # ### end Alembic commands ###
