"""add etf_fundamental table

Revision ID: f76057e3b7e5
Revises: c49474451233
Create Date: 2026-01-25 15:15:08.804684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76057e3b7e5'
down_revision: Union[str, None] = 'c49474451233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etf_fundamental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('fund_provider', sa.String(), nullable=True),
    sa.Column('core_metadata', sa.JSON(), nullable=True),
    sa.Column('holdings', sa.JSON(), nullable=True),
    sa.Column('sector_allocation', sa.JSON(), nullable=True),
    sa.Column('country_allocation', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin', name='uq_etf_fundamental_isin')
    )
    op.create_index(op.f('ix_etf_fundamental_fund_provider'), 'etf_fundamental', ['fund_provider'], unique=False)
    op.create_index(op.f('ix_etf_fundamental_id'), 'etf_fundamental', ['id'], unique=False)
    op.create_index(op.f('ix_etf_fundamental_isin'), 'etf_fundamental', ['isin'], unique=False)
    op.create_index(op.f('ix_etf_fundamental_ticker'), 'etf_fundamental', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etf_fundamental_ticker'), table_name='etf_fundamental')
    op.drop_index(op.f('ix_etf_fundamental_isin'), table_name='etf_fundamental')
    op.drop_index(op.f('ix_etf_fundamental_id'), table_name='etf_fundamental')
    op.drop_index(op.f('ix_etf_fundamental_fund_provider'), table_name='etf_fundamental')
    op.drop_table('etf_fundamental')
    # ### end Alembic commands ###
